services:
   postgres:
      image: postgres:16.2
      ports:
         - 5432:5432
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=user1
         - POSTGRES_DB=ailibrary
      # healthcheck:
      #    test: ["CMD", "pg_isready", "-U", "user1"]
      volumes:
         - prm_data:/var/lib/postgresql/data
volumes:
   prm_data:
      driver: local
