services:
   app:
      build:
         context: ../.
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      environment:
         NODE_ENV: production
         DATABASE_URL: postgresql://user1:test@localhost:5432/ailibrary

         # Auth
         AUTH_SECRET: ${AUTH_SECRET:-Aiz4c+4Dnf73sUe5bVqufL9hcmGBJYGNF/P0GsiJ1Uk=}
         AUTH_URL: ${AUTH_URL:-http://localhost:3000}
         NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL:-http://app:3000}
         ENCRYPTION_KEY: ${ENCRYPTION_KEY:-SxhULoMRflRMqDrr4FAsQ+RCEY4vMiC0lCXkth87eIU=}

         # App
         NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-KI Bibliothek}
         NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-http://localhost:3000}
         NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}

         # Stripe
         NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_51Q0isdGzyOS6MDj9jupMzmMbVOY7gY4YJqASAOOsBRDOT1zFriorzVEHJ01OLpit8466us18VrT0T1MJcVORpwMy00kvVlPbCo}
         STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_51Q0isdGzyOS6MDj9oYHbn9aJ0Sg345BEEnShqffhJN3KkEeJJLs2JZkN5ehokIYkBNaHvIbiRHZKPu2CU0iakZEd00fh8FB4QH}
         STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_a20319e73f73437fb80be610305e42b2741a5c8d81c531e391931b1d0e7a0603}
      depends_on:
         postgres:
            condition: service_healthy
      restart: unless-stopped

   postgres:
      image: postgres:16.2
      ports:
         - 5432:5432
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=user1
         - POSTGRES_DB=ailibrary
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U user1 -d ailibrary"]
         interval: 5s
         timeout: 5s
         retries: 10
      volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
      driver: local
