services:
   # ai-library-db-migration:
   #    build:
   #       context: ../.
   #       dockerfile: Dockerfile
   #       target: dbmigrations
   #    environment:
   #       DATABASE_URL: postgresql://user1:test@postgres:5432/ailibrary
   #    depends_on:
   #       postgres:
   #          condition: service_healthy
   #    restart: on-failure
   # ai-library-db-dbdatainit:
   #    build:
   #       context: ../.
   #       dockerfile: Dockerfile
   #       target: dbdatainit
   #    environment:
   #       DATABASE_URL: postgresql://user1:test@postgres:5432/ailibrary
   #    depends_on:
   #       ai-library-db-migration:
   #          condition: service_completed_successfully
   #    restart: on-failure

   # ai-library:
   #    build:
   #       context: ../.
   #       dockerfile: Dockerfile
   #    ports:
   #       - "3000:3000"
   #    tty: true # Keeps the container running for debugging
   #    environment:
   #       NODE_ENV: production
   #       DATABASE_URL: postgresql://user1:test@postgres:5432/ailibrary

   #       # Auth
   #       AUTH_SECRET: ${AUTH_SECRET:-Aiz4c+4Dnf73sUe5bVqufL9hcmGBJYGNF/P0GsiJ1Uk=}
   #       AUTH_URL: ${AUTH_URL:-http://localhost:3000}
   #       NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL:-http://app:3000}
   #       ENCRYPTION_KEY: ${ENCRYPTION_KEY:-SxhULoMRflRMqDrr4FAsQ+RCEY4vMiC0lCXkth87eIU=}

   #       # Next Public
   #       NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-Vision Notes}
   #       NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-http://localhost:3000}

   #       # App
   #       APP_URL: ${APP_URL:-http://localhost:3000}

   #       # Stripe
   #       NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_51Q0isdGzyOS6MDj9jupMzmMbVOY7gY4YJqASAOOsBRDOT1zFriorzVEHJ01OLpit8466us18VrT0T1MJcVORpwMy00kvVlPbCo}
   #       STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_51Q0isdGzyOS6MDj9oYHbn9aJ0Sg345BEEnShqffhJN3KkEeJJLs2JZkN5ehokIYkBNaHvIbiRHZKPu2CU0iakZEd00fh8FB4QH}
   #       STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_a20319e73f73437fb80be610305e42b2741a5c8d81c531e391931b1d0e7a0603}

   #       # IUBENdA
   #       IUBENDA_API_KEY: ${IUBENDA_API_KEY:-mock-iubenda-api-key-123}
   #       IUBENDA_CONSENT_URL: ${IUBENDA_CONSENT_URL:-https://iubenda.test.com}

   #       # BREVO
   #       EMAIL_PROVIDER: ${EMAIL_PROVIDER:-SMTP}
   #       BREVO_API_KEY: ${BREVO_API_KEY:-mock-brevo-api-key-123}
   #       BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL:-info@vision-notes.com}

   #       # SMTP
   #       SMTP_HOST: ${SMTP_PORT:-mailhog}
   #       SMTP_PORT: ${SMTP_PORT:-1025}
   #       SMTP_FROM: ${SMTP_PORT:-noreply@mailhog}
   #    depends_on:
   #       postgres:
   #          condition: service_healthy
   #       ai-library-db-migration:
   #          condition: service_completed_successfully
   #    restart: unless-stopped

   mailhog:
      image: mailhog/mailhog:latest
      ports:
         - "1025:1025" # SMTP
         - "8025:8025" # Web UI → http://localhost:8025
      restart: unless-stopped

   postgres:
      image: postgres:16.2
      ports:
         - 5432:5432
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=user1
         - POSTGRES_DB=ailibrary
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U user1 -d ailibrary"]
         interval: 5s
         timeout: 5s
         retries: 10
      volumes:
         - postgres_data:/var/lib/postgresql/data
      restart: unless-stopped

   # prisma-studio:
   #    image: node:22-alpine
   #    ports:
   #       - "5555:5555"
   #    command: npx prisma studio --port 5555 --browser none
   #    depends_on:
   #       postgres:
   #          condition: service_healthy
   #       ai-library:
   #          condition: service_started

volumes:
   postgres_data:
      driver: local
