name: CI/CD Pipeline

on:
   workflow_call:
   pull_request:
      types: [opened, reopened]

jobs:
   run-validations:
      runs-on: ubuntu-24.04
      permissions:
         contents: read
         checks: write
         pull-requests: write
      env:
         DATABASE_URL: "postgres://localhost:51213"
      steps:
         - name: Setup Node v22
           uses: actions/setup-node@v4
           with:
              node-version: v22

         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Secret Scanner
           uses: secret-scanner/action@0.0.2
           with:
              baseline-file: .github/data/.secrets.baseline

         - name: Install Dependencies
           run: npm ci

         - name: Run Tests
           run: npm run test -- --coverage

         - name: Upload Test Coverage Results
           if: always()
           uses: actions/upload-artifact@v6
           with:
              name: coverage
              path: coverage/
              retention-days: 1

         - name: Report Coverage
           if: always() && github.event_name == 'pull_request'
           uses: MishaKav/jest-coverage-comment@main
           with:
              coverage-summary-path: ./coverage/coverage-summary.json
              title: Test Coverage
