name: CI/CD Pipeline

on:
   workflow_call:
   pull_request:
      types: [opened, reopened]

jobs:
   run-validations:
      runs-on: ubuntu-24.04
      permissions:
         contents: read
         checks: write
         pull-requests: write
      env:
         DATABASE_URL: "postgres://localhost:51213"
      steps:
         - name: Setup Node v22
           uses: actions/setup-node@v4
           with:
              node-version: v22

         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Secret Scanner
           uses: secret-scanner/action@0.0.2
           with:
              baseline-file: .github/data/.secrets.baseline

         - name: Install Dependencies
           run: npm ci

         # - name: npm build
         #   run: npm run build

         # - name: run Lighthouse CI
         #   run: |
         #      npm install -g @lhci/cli@0.15.1
         #      npm run test:lhci
         #   env:
         #      LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Run Tests
           run: npm run test

         - name: Report Coverage
           if: always()
           uses: ArtiomTr/jest-coverage-report-action@v2
           with:
              coverage-file: ./coverage/coverage-summary.json
              output: ${{ github.event_name == 'pull_request' && 'comment' || 'report-markdown' }}
