name: Release Pipeline

on:
   release:
      types: [published]

env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}

jobs:
   ci:
      uses: ./.github/workflows/ci.yaml
      permissions:
         contents: read
         checks: write
         pull-requests: write
   build-and-push-image:
      runs-on: ubuntu-24.04
      # needs: ci
      permissions:
         contents: write
         packages: write
         attestations: write
         id-token: write
         checks: write
      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Login to Github Container registry
           uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Retrieve metadata for DB Migrations Docker Image
           id: db-migrations-meta
           uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
           with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-db-migrations

         - name: Build and push DB Migrations Docker Image
           id: push-dbmigrations
           uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
           with:
              context: .
              target: dbmigrations
              push: ${{ github.event_name == 'release' }}
              tags: ${{ steps.db-migrations-meta.outputs.tags }}
              labels: ${{ steps.db-migrations-meta.outputs.labels }}

         - name: Retrieve metadata for App Docker Image
           id: app-meta
           uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
           with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

         - name: Build and push App Docker Image
           id: push-app
           uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
           with:
              context: .
              push: ${{ github.event_name == 'release' }}
              tags: ${{ steps.app-meta.outputs.tags }}
              labels: ${{ steps.app-meta.outputs.labels }}

         # - name: Generate artifact attestation
         #   uses: actions/attest-build-provenance@v1
         #   with:
         #      subject-name: ${{ steps.meta.outputs.tags }}
         #      subject-digest: ${{ steps.push.outputs.digest }}
         #      push-to-registry: true
